generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbbibliography
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbbibliography
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_bibliography:    {label: Id}
        id_crop:            {label: Crop}
        id_trialgroup:      {label: Trial Group}
        id_language:        {label: Language}
        bbgreferencetype:   {label: Reference type}
        bbgtitle:           {label: Title}
        bbgauthor:          {label: Author}
        bbgvolume:          {label: Volume}
        bbgnumber:          {label: Number}
        bbgyear:            {label: Year}
        bbgdocumenttitle:   {label: Document title}
        bbgpublisher:       {label: Publisher}
        bbgpages:           {label: Pages}
        bbgabstract:        {label: Abstract}
        bbgkeywords:        {label: Keywords}
        bbgnotes:           {label: Notes}
        bbgaddedtolibrary:  {label: Added to library}

      #Configuracion para Lista de Registros
      list:
        title:          List Bibliography
        max_per_page:   20
        display:        [id_bibliography, _crop, _trialgroup, _language, bbgreferencetype, bbgtitle]
        fields:
          id_bibliography:   {label: Id}
          crop:              {label: Crop}
          trialgroup:        {label: Trial Group}
          language:          {label: Language}
          bbgreferencetype:  {label: Reference type}
          bbgtitle:          {label: Title}
          
        object_actions:
          _edit:   ~
          _show:   ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Bibliography

      #Configuracion para Nuevo Registro
      new:
        title:          New Bibliography

      #Configuracion para la Vista de Registro
      show:
        title:          Show Bibliography