generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbcountry
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbcountry
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      
      #Configuracion Etiqueta Campos
      fields:
        id_country:  {label: id}
        cntname:     {label: Name}
        cntiso:      {label: Iso}
        cntiso3:     {label: Iso 3}
        cntnumcode:  {label: Number code}

      #Configuracion para Lista de Registros
      list:
        title:          List Country
        max_per_page:   20
        display:        [id_country,cntname,cntiso,cntiso3]
        fields:
          id_country:  {label: id}
          cntname:     {label: Name}
          cntiso:      {label: Iso}
          cntiso3:     {label: Iso 3}
        object_actions: {}
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:
         #Configuracion Acciones Formulario 
        actions:  ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Country

      #Configuracion para Nuevo Registro
      new:
        title:          New Country

