generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbtrialgrouptype
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbtrialgrouptype
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_trialgrouptype:  {label: Id}
        trgptyname:         {label: Name}

      #Configuracion para Lista de Registros
      list:
        title:          List Trial Group Type
        max_per_page:   20
        display:        [id_trialgrouptype, trgptyname]
        fields:
          id_trialgrouptype: {label: Id}
          trgptyname:      {label: Name}
        object_actions: 
          _edit:        ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Trial Group Type

      #Configuracion para Nuevo Registro
      new:
        title:          New Trial Group Type

