<?php

/**
 * TbBibliography
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    trialsites
 * @subpackage model
 * @author     Herlin R. Espinosa G. - CIAT-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TbBibliography extends BaseTbBibliography {

    //INICIO FUNCION PARA GRABAR O ACTUALIZAR
    public function save(Doctrine_Connection $conn = null) {
        //CONVERSION DE TEXTOS (MAYUSCULA - minuscula - Primera palabra en mayuscula)
        $this->setBbgtitle(ucfirst(strtolower($this->getBbgtitle())));
        //$this->setBbgauthor(ucwords($this->getBbgauthor()));
        $this->setBbgvolume(ucfirst(strtolower($this->getBbgvolume())));
        $this->setBbgnumber(ucfirst(strtolower($this->getBbgnumber())));
        $this->setBbgyear(ucfirst(strtolower($this->getBbgyear())));
        $this->setBbgdocumenttitle(ucfirst(strtolower($this->getBbgdocumenttitle())));
        $this->setBbgpublisher(ucfirst(strtolower($this->getBbgpublisher())));
        $this->setBbgpages(ucfirst(strtolower($this->getBbgpages())));
       // $this->setBbgabstract(ucfirst(strtolower($this->getBbgabstract())));
        //$this->setBbgkeywords(ucwords($this->getBbgkeywords()));
        //$this->setBbgnotes(ucwords($this->getBbgnotes()));

        //REGISTRO DE USUARIO DE CREACION O ACTUALIZACION
        $id_user = sfContext::getInstance()->getUser()->getAttribute('user_id', '', 'sfGuardSecurityUser');
        if ($this->isNew()) {
            $this->setIdUser($id_user);
            $this->setIdUserUpdate(null);
        } else {
            if ($this->getIdUser() == null)
                $this->setIdUser(null);
            $this->setIdUserUpdate($id_user);
        }

        return parent::save($conn);
    }

    //CONFIGURACION PARA GUARDAR CREATE AT Y UPDATE AT
    public function setUp() {
        parent::setUp();
        $this->hasOne('TbTrialgroup', array(
            'local' => 'id_trialgroup',
            'foreign' => 'id_trialgroup'));

        $this->hasOne('TbLanguage', array(
            'local' => 'id_language',
            'foreign' => 'id_language'));

        $this->hasOne('TbCrop', array(
            'local' => 'id_crop',
            'foreign' => 'id_crop'));

        $timestampable0 = new Doctrine_Template_Timestampable(array());
        $this->actAs($timestampable0);
    }

}