<?php

/**
 * TbFieldnamenumber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    trialsites
 * @subpackage model
 * @author     Herlin R. Espinosa G. - CIAT-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TbFieldnamenumber extends BaseTbFieldnamenumber {

    public function __toString() {
        return $this->getTrialenvironmentname();
    }

    //INICIO FUNCION PARA GRABAR O ACTUALIZAR
    public function save(Doctrine_Connection $conn = null) {
        //CONVERSION DE TEXTOS (MAYUSCULA - minuscula - Primera palabra en mayuscula)
        $this->setTrialenvironmentname(ucfirst(strtolower($this->getTrialenvironmentname())));

        //REGISTRO DE USUARIO DE CREACION O ACTUALIZACION
        $id_user = sfContext::getInstance()->getUser()->getAttribute('user_id', '', 'sfGuardSecurityUser');
        if ($this->isNew()) {
            $this->setIdUser($id_user);
            $this->setIdUserUpdate(null);
        } else {
            if ($this->getIdUser() == null)
                $this->setIdUser(null);
            $this->setIdUserUpdate($id_user);
        }

        return parent::save($conn);
    }

    //CONFIGURACION PARA GUARDAR CREATE AT Y UPDATE AT
    public function setUp() {
        parent::setUp();
        $this->hasOne('TbTrialenvironmenttype', array(
            'local' => 'id_trialenvironmenttype',
            'foreign' => 'id_trialenvironmenttype'));

        $this->hasOne('TbTrialsite', array(
            'local' => 'id_trialsite',
            'foreign' => 'id_trialsite'));

        $this->hasOne('TbTaxonomyfao', array(
            'local' => 'id_taxonomyfao',
            'foreign' => 'id_taxonomyfao'));

        $this->hasOne('TbSoil', array(
            'local' => 'id_soil',
            'foreign' => 'id_soil'));

        $this->hasMany('TbTrial', array(
            'local' => 'id_fieldnamenumber',
            'foreign' => 'id_fieldnamenumber'));

        $timestampable0 = new Doctrine_Template_Timestampable(array());
        $this->actAs($timestampable0);
    }

}

