<?php

/**
 * TbInstitution
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    trialsites
 * @subpackage model
 * @author     Herlin R. Espinosa G. - CIAT-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TbInstitution extends BaseTbInstitution {

    public function __toString() {
        return $this->getInsname();
    }

    //INICIO FUNCION PARA GRABAR O ACTUALIZAR
    public function save(Doctrine_Connection $conn = null) {
        //PASAMOS TODO EL TEXTO A PRIMERA EN MAYUSCULA Y SOLO MINUSCULA
        $this->setInsname(strtoupper($this->getInsname()));
        $this->setInsaddress(ucfirst(strtolower($this->getInsaddress())));
        $this->setInsphone(strtolower($this->getInsphone()));
        $this->setInsfax(strtolower($this->getInsfax()));
        $this->setInsemail(strtolower($this->getInsemail()));
        $this->setInswebsite(strtolower($this->getInswebsite()));

        //REGISTRO DE USUARIO DE CREACION O ACTUALIZACION
        $id_user = sfContext::getInstance()->getUser()->getAttribute('user_id', '', 'sfGuardSecurityUser');
        if ($this->isNew()) {
            $this->setIdUser($id_user);
            $this->setIdUserUpdate(null);
        } else {
            if ($this->getIdUser() == null)
                $this->setIdUser(null);
            $this->setIdUserUpdate($id_user);
        }

        return parent::save($conn);
    }

    //CONFIGURACION PARA GUARDAR CREATE AT Y UPDATE AT
    public function setUp() {
        parent::setUp();
        $this->hasOne('TbCountry', array(
            'local' => 'id_country',
            'foreign' => 'id_country'));

        $this->hasMany('TbContactperson', array(
            'local' => 'id_institution',
            'foreign' => 'id_institution'));

        $this->hasMany('TbInstitutionnetwork', array(
            'local' => 'id_institution',
            'foreign' => 'id_institution'));

        $this->hasMany('TbOrigin', array(
            'local' => 'id_institution',
            'foreign' => 'id_institution'));

        $this->hasMany('TbTrialgroup', array(
            'local' => 'id_institution',
            'foreign' => 'id_institution'));

        $this->hasMany('TbTrialsite', array(
            'local' => 'id_institution',
            'foreign' => 'id_institution'));

        $timestampable0 = new Doctrine_Template_Timestampable(array());
        $this->actAs($timestampable0);
    }

}