generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tborigin
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tborigin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:       ~
      #Configuracion Etiqueta Campos
      fields:
        id_origin:        {label: Id}
        id_country:       {label: Country}
        orgname:          {label: Name}
        id_institution :  {label: Institution}

      #Configuracion para Lista de Registros
      list:
        title:          List Origin
        max_per_page:   20
        display:        [id_origin, _country, orgname, _institution]
        fields:
          id_origin:     {label: Id}
          country:       {label: Country}
          orgname:       {label: Name}
          institution :  {label: Institution }
        object_actions: {}
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Origin

      #Configuracion para Nuevo Registro
      new:
        title:          New Origin

