New:
  is_secure:   on        # La acción "Nuevo" es sólo para usuarios autenticados

Edit:
  is_secure:   on        # La acción "Editar" es sólo para usuarios autenticados

Delete:
  is_secure:   on        # La acción "Eliminar" es sólo para usuarios autenticados
  
Index:
  is_secure:   on        # La acción "Lista" es sólo para usuarios autenticados
  
_Add_trial:
  is_secure:   on        # La acción "Adicionar Trial" es sólo para usuarios autenticados

batchuploadtrialgroup:
  is_secure:   on        # La acción es sólo para usuarios autenticados
