generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbweatherstation
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbweatherstation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_weatherstation:       {label: Id}
        id_country:              {label: Country}
        id_institution:          {label: Institution}
        id_contactperson:        {label: Contact person}
        wtstname:                {label: Name}
        wtstlatitude:            {label: Latitude (Decimal)}
        wtstlongitude:           {label: Longitude (Decimal)}
        wtstelevation:           {label: Elevation (M)}
        wtstrestricted:          {label: "Access Restricted?"}
        wtstlicence:             {label: Access and Use Constraints}
        id_weatherstationsource: {label: Source of data}

      #Configuracion para Lista de Registros
      list:
        title:          List Weather Station
        max_per_page:   20
        display:        [id_weatherstation, _country, wtstname, wtstlatitude, wtstlongitude, wtstelevation]
        fields:
          id_weatherstation:     {label: Id}
          country:               {label: Country}
          wtstname:              {label: Name}
          wtstlatitude:          {label: Latitude}
          wtstlongitude:         {label: Longitude}
          wtstelevation:         {label: Elevation}
        
        object_actions:
          _edit:        ~
          _show:        ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Weather Station

      #Configuracion para Nuevo Registro
      new:
        title:          New Weather Station

      #Configuracion para la Vista del Registro
      show:
        title:          View Weather Station