generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbunit
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbunit
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_unit:         {label: Id}
        untname:         {label: Name}
        untdescription:  {label: Description}

      #Configuracion para Lista de Registros
      list:
        title:          List Units
        max_per_page:   20
        display:        ~
        object_actions:
          _edit:        ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Units

      #Configuracion para Nuevo Registro
      new:
        title:          New Units
