generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbcontactpersontype
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbcontactpersontype
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_contactpersontype:  {label: Id}
        ctprtpname:            {label: Name}

      #Configuracion para Lista de Registros
      list:
        title:          List Contact Person Type
        max_per_page:   20
        display:        [id_contactpersontype, ctprtpname]
        fields:
          id_objective: {label: Id}
          id_contactpersontype:      {label: Name}
        object_actions: 
          _edit:        ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Contact Person Type

      #Configuracion para Nuevo Registro
      new:
        title:          New Contact Person Type
