New:
  is_secure:   on        # La acción "Nuevo" es sólo para usuarios autenticados

Edit:
  is_secure:   on        # La acción "Editar" es sólo para usuarios autenticados

Delete:
  is_secure:   on        # La acción "Eliminar" es sólo para usuarios autenticados
  
Index:
  is_secure:   on        # La acción "Lista" es sólo para usuarios autenticados

checktrialsite:
  is_secure:   on        # La acción es sólo para usuarios autenticados

checktrialsitebatch:
  is_secure:   on        # La acción es sólo para usuarios autenticados

resultfilechecktrialsite:
  is_secure:   on        # Es sólo para usuarios autenticados
  
batchuploadtrialsite:
  is_secure:   on        # La acción es sólo para usuarios autenticados
  
maptrialsites:
  is_secure:   on        # La acción es sólo para usuarios autenticados
  
downloadlist:
  is_secure:   on        # La acción es sólo para usuarios autenticados