generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbvariety
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbvariety
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:       ~

      #Configuracion Etiqueta Campos
      fields:
        id_variety:     {label: id}
        id_crop:        {label: Technology}
        id_origin:      {label: Origin}
        vrtname:        {label: Name}
        vrtsynonymous:  {label: Synonym}
        vrtdescription: {label: Description}

      #Configuracion para Lista de Registros
      list:
        title:          List Variety/Race
        max_per_page:   20
        display:        [ id_variety, _crop, _origin, vrtname, vrtsynonymous]
        fields:
          id_variety:     {label: id}
          crop:           {label: Technology}
          origin:         {label: Origin}
          vrtname:        {label: Name}
          vrtsynonymous:  {label: Synonym}
        #object_actions: {}
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Variety/Race

      #Configuracion para Nuevo Registro
      new:
        title:          New Variety/Race
