generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbfieldnamenumber
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbfieldnamenumber
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_fieldnamenumber:       {label: Id}
        id_trialsite:             {label: Trial site}
        id_trialenvironmenttype:  {label: Trial environment type}
        trialenvironmentname:     {label: Trial environment name}
        finanulatitudedecimal:    {label: Latitude}
        finanulongitudedecimal:   {label: Longitude}
        finanualtitude:           {label: Altitude}
        finanuph:                 {label: Ph}
        id_soil:                  {label: Soil texture}
        id_taxonomyfao:           {label: Taxonomy FAO}

         #Configuracion para Lista de Registros
      list:
        title:          List Field name number
        max_per_page:   20
        display:        [id_fieldnamenumber, _trialsite, id_trialenvironmenttype, trialenvironmentname, finanulatitudedecimal, finanulongitudedecimal, finanualtitude]
        fields:
          id_fieldnamenumber:      {label: Id}
          trialsite:               {label: Trial site}
          id_trialenvironmenttype: {label: Trial environmentt type}
          trialenvironmentname:    {label: Trial environment name}
          finanulatitudedecimal:   {label: Latitud}
          finanulongitudedecimal:  {label: Longitud}
          finanualtitude:          {label: Altitud}
        object_actions:
          _edit:        ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Field name number

      #Configuracion para Nuevo Registro
      new:
        title:          New Field name number
