New:
  is_secure:   on        # La acción "Nuevo" es sólo para usuarios autenticados

Edit:
  is_secure:   on        # La acción "Editar" es sólo para usuarios autenticados

Delete:
  is_secure:   on        # La acción "Eliminar" es sólo para usuarios autenticados