generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tbtrialenvironmenttype
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tbtrialenvironmenttype
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_trialenvironmenttype:  {label: Id}
        trnvtyname:               {label: Name}

      #Configuracion para Lista de Registros
      list:
        title:          List Trial Environment Type
        max_per_page:   20
        display:        [id_trialenvironmenttype, trnvtyname]
        fields:
          id_trialenvironmenttype: {label: Id}
          trnvtyname:              {label: Name}
        object_actions: 
          _edit:        ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Trial Environment Type

      #Configuracion para Nuevo Registro
      new:
        title:          New Trial Environment Type

