Index:
  is_secure:   on        # La acci贸n "Index" es s贸lo para usuarios autenticados
  
Trialssitesbycrop:
  is_secure:   on        # La acci贸n "Trialssitesbycrop" es s贸lo para usuarios autenticados
