generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tblocation
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tblocation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:          ~
      #Configuracion Etiqueta Campos
      fields:
        id_location:  {label: Id}
        id_country:   {label: Country}
        lctname:      {label: Name}

      #Configuracion para Lista de Registros
      list:
        title:          List Location
        max_per_page:   20
        display:        [id_location, _country,	lctname]
        fields:
          id_location:  {label: Id}
          country:      {label: Country}
          lctname:      {label: Name}
        object_actions:
          _edit:        ~
        batch_actions:  {}

      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Location

      #Configuracion para Nuevo Registro
      new:
        title:          New Location
